		CASE ROUND(RANDOM() * 25)
			WHEN 0 THEN 'Denesikport - TN'
			WHEN 1 THEN 'Winston-Salem - ID'
			WHEN 2 THEN 'Port Juliomouth - NE'
			WHEN 3 THEN 'Mantestead - TX'
			WHEN 4 THEN 'Ortizcester - MD'
			WHEN 5 THEN 'Sanfordville - VT'
			WHEN 6 THEN 'Tobintown - TX'
			WHEN 7 THEN 'West Lauryn - NV'
			WHEN 8 THEN 'Hettingerfield - OH'
			WHEN 9 THEN 'South Dalton - CA'
			WHEN 10 THEN 'Townemouth - CA'
			WHEN 11 THEN 'Port Sam - AL'
			WHEN 12 THEN 'North Estelbury - WV'
			WHEN 13 THEN 'East Zackary - WA'
			WHEN 14 THEN 'Port Demarco - TN'
			WHEN 15 THEN 'Farmington - NY'
			WHEN 16 THEN 'Gutkowskihaven - GA'
			WHEN 17 THEN 'West Jonatanton - NE'
			WHEN 18 THEN 'Holliemouth - NV'
			WHEN 19 THEN 'Poway - WI'
			WHEN 20 THEN 'Gersontown - HI'
			WHEN 21 THEN 'Ebertbury - AZ'
			WHEN 22 THEN 'Fort Brisa - NH'
			WHEN 23 THEN 'Schneiderfurt - GA'
			WHEN 24 THEN 'Vedastad - ID'
			WHEN 25 THEN 'Lake Titoberg - WY'
		END cidade